// Every user-facing text, centralized. Code stays in English; UI in Spanish.

export const STR = {
  app: {
    title: 'TETRIS · IA',
    subtitle: 'Evolución en directo',
    footer: 'v1.0',
    loading: 'Cargando…',
  },

  menu: {
    play: 'Jugar',
    training: 'Entrenamiento IA',
    watch: 'Ver IA',
    records: 'Récords',
    settings: 'Ajustes',
    hint: 'Navega con ↑ ↓ y Enter, o haz clic',
  },

  common: {
    back: 'Volver',
    close: 'Cerrar',
    cancel: 'Cancelar',
    accept: 'Aceptar',
    save: 'Guardar',
    delete: 'Eliminar',
    rename: 'Renombrar',
    export: 'Exportar',
    import: 'Importar',
    confirm: 'Confirmar',
    yes: 'Sí',
    no: 'No',
    on: 'Sí',
    off: 'No',
    reset: 'Restaurar',
    pause: 'Pausa',
    resume: 'Continuar',
    restart: 'Reiniciar',
    menu: 'Menú principal',
    level: 'Nivel',
    lines: 'Líneas',
    score: 'Puntos',
    time: 'Tiempo',
    pieces: 'Piezas',
    seed: 'Semilla',
    speed: 'Velocidad',
    name: 'Nombre',
    date: 'Fecha',
    none: '—',
    error: 'Error',
    warning: 'Aviso',
    unsavedWarning: 'Hay trabajo sin guardar. ¿Seguro que quieres salir?',
  },

  game: {
    hold: 'Reserva',
    next: 'Siguientes',
    ghost: 'Fantasma',
    combo: 'Combo',
    b2b: 'Seguidas (B2B)',
    pps: 'PPS',
    finesse: 'Precisión',
    gameOver: 'FIN DE PARTIDA',
    victory: '¡OBJETIVO CUMPLIDO!',
    ready: 'Preparado',
    countdown: ['3', '2', '1', '¡YA!'],
    paused: 'PAUSA',
    dangerWarning: '¡Peligro!',
    toasts: {
      single: 'SIMPLE',
      double: '¡DOBLE!',
      triple: '¡TRIPLE!',
      tetris: '¡¡TETRIS!!',
      tspin: '¡T-SPIN!',
      tspinMini: 'T-SPIN MINI',
      tspinSingle: '¡T-SPIN SIMPLE!',
      tspinDouble: '¡T-SPIN DOBLE!',
      tspinTriple: '¡T-SPIN TRIPLE!',
      b2b: '¡SEGUIDAS ×{n}!',
      combo: 'COMBO ×{n}',
      allClear: '¡¡PERFECT CLEAR!!',
      levelUp: 'NIVEL {n}',
      zenReset: 'Tablero limpio — sigue en zen',
    },
    overReasons: {
      blockout: 'Bloqueo en la zona de aparición',
      lockout: 'Pieza fijada fuera del tablero',
      topout: 'La pila llegó arriba',
      time: 'Tiempo agotado',
      goal: 'Objetivo alcanzado',
    },
  },

  modes: {
    title: 'Elige modo de juego',
    marathon: { name: 'Maratón', desc: '150 líneas con curva de niveles completa' },
    sprint: { name: 'Sprint 40', desc: 'Limpia 40 líneas a contrarreloj' },
    ultra: { name: 'Ultra 2:00', desc: 'Máxima puntuación en 2 minutos' },
    zen: { name: 'Zen', desc: 'Sin fin de partida, sin presión' },
    cheese: { name: 'Excavación', desc: 'Excava las líneas de basura' },
    endless: { name: 'Infinito', desc: 'Hasta que la pila te alcance' },
    best: 'Mejor marca',
    lastResult: 'Último resultado',
    start: 'Empezar',
    startLevel: 'Nivel inicial',
    cheeseRows: 'Filas de basura',
  },

  summary: {
    title: 'Resumen de la partida',
    breakdown: 'Desglose de puntos',
    clearPoints: 'Limpiezas',
    tspinPoints: 'T-spins',
    comboPoints: 'Combos',
    b2bBonus: 'Bonus B2B',
    allClearPoints: 'Perfect clears',
    dropPoints: 'Caídas',
    pieceDistribution: 'Distribución de piezas',
    tetrisRate: 'Tasa de tetris',
    finesseRate: 'Precisión de inputs',
    newRecord: '¡NUEVO RÉCORD!',
    enterName: 'Escribe tu nombre',
    retry: 'Reintentar',
    playAgainSeed: 'Repetir semilla',
    watchReplay: 'Ver repetición',
    vsBest: 'frente a tu mejor marca',
  },

  records: {
    title: 'Récords',
    empty: 'Aún no hay récords en este modo. ¡Juega una partida!',
    lifetime: 'Estadísticas históricas',
    totalGames: 'Partidas jugadas',
    totalLines: 'Líneas totales',
    totalPieces: 'Piezas colocadas',
    totalTetrises: 'Tetris totales',
    totalTspins: 'T-spins totales',
    totalTime: 'Tiempo jugado',
    maxCombo: 'Mejor combo',
    replays: 'Repeticiones',
    watchReplay: 'Ver',
    noReplay: 'Sin repetición',
  },

  replay: {
    title: 'Repetición',
    speed: 'Velocidad',
    piece: 'Pieza',
    finished: 'Fin de la repetición',
  },

  settings: {
    title: 'Ajustes',
    tabs: {
      controls: 'Controles',
      game: 'Juego',
      video: 'Vídeo',
      audio: 'Audio',
      data: 'Datos',
    },
    controls: {
      keyboard: 'Teclado',
      gamepad: 'Mando',
      pressKey: 'Pulsa una tecla…',
      conflict: 'Tecla ya asignada a {action}',
      restore: 'Restaurar por defecto',
      gamepadDetected: 'Mando detectado: {name}',
      gamepadNone: 'Ningún mando detectado. Conecta uno y pulsa un botón.',
      actions: {
        moveLeft: 'Mover izquierda',
        moveRight: 'Mover derecha',
        softDrop: 'Caída suave',
        hardDrop: 'Caída instantánea',
        rotateCW: 'Rotar horario',
        rotateCCW: 'Rotar antihorario',
        rotate180: 'Rotar 180°',
        hold: 'Reserva',
        pause: 'Pausa',
        restart: 'Reiniciar',
      },
    },
    game: {
      das: 'DAS (retardo de repetición)',
      arr: 'ARR (velocidad de repetición)',
      sdf: 'SDF (factor de caída suave)',
      ghost: 'Pieza fantasma',
      previews: 'Piezas siguientes visibles',
      ms: 'ms',
    },
    video: {
      theme: 'Tema visual',
      themes: { neon: 'Neón', classic: 'Clásico', minimal: 'Minimal' },
      particles: 'Partículas',
      screenShake: 'Vibración de pantalla',
      shakeLevels: { off: 'No', soft: 'Suave', strong: 'Fuerte' },
      reducedMotion: 'Reducir movimiento',
      highContrast: 'Alto contraste',
      colorblind: 'Modo daltónico (letras en piezas)',
    },
    audio: {
      sfx: 'Efectos de sonido',
      music: 'Música',
      sfxVolume: 'Volumen de efectos',
      musicVolume: 'Volumen de música',
      mute: 'Silenciar todo',
    },
    data: {
      exportAll: 'Exportar ajustes y récords',
      importAll: 'Importar ajustes y récords',
      importOk: 'Datos importados correctamente',
      importBad: 'El fichero no contiene datos válidos',
      storage: 'Almacenamiento de modelos',
      modelsCount: '{n} modelos · {m} sesiones guardadas',
      clearAll: 'Borrar todos los datos',
      clearAllConfirm1: '¿Borrar TODOS los datos (ajustes, récords, modelos, sesiones)?',
      clearAllConfirm2: 'Esta acción no se puede deshacer. ¿Borrar definitivamente?',
      cleared: 'Todos los datos han sido borrados',
    },
  },

  training: {
    title: 'Entrenamiento IA',
    configTitle: 'Configuración del entrenamiento',
    evolution: 'Evolución',
    agentCol: 'Agente y fitness',
    population: 'Población',
    elitism: 'Elitismo',
    tournament: 'Tamaño de torneo',
    mutationRate: 'Tasa de mutación',
    mutationSigma: 'Sigma de mutación',
    crossover: 'Cruce',
    crossoverOps: { uniform: 'Uniforme', blx: 'BLX-α', none: 'Sin cruce' },
    crossoverRate: 'Probabilidad de cruce',
    masterSeed: 'Semilla maestra',
    randomSeed: 'Aleatoria',
    seedsPerEval: 'Partidas por evaluación',
    inputFeatures: 'Features de entrada',
    architecture: 'Arquitectura de red',
    hiddenLayers: 'Capas ocultas',
    neurons: 'Neuronas',
    weightsTotal: '{n} pesos totales',
    useHold: 'La IA puede usar la reserva',
    fitnessWeights: 'Pesos de la función de fitness',
    fitnessKeys: {
      lines: 'Por línea',
      tetrises: 'Por tetris',
      tspins: 'Por T-spin',
      pieces: 'Por pieza colocada',
      scoreSqrt: '√puntos',
    },
    presets: 'Preajustes',
    presetNames: { fast: 'Rápido', balanced: 'Equilibrado', deep: 'Profundo' },
    savePreset: 'Guardar preajuste…',
    presetName: 'Nombre del preajuste',
    sessionName: 'Nombre de la sesión',
    warmStart: 'Empezar desde modelo…',
    warmStartNone: 'Desde cero (aleatorio)',
    resumeSession: 'Reanudar sesión guardada…',
    stopConditions: 'Parada automática',
    maxGenerations: 'Generación máxima',
    targetFitness: 'Fitness objetivo',
    noLimit: 'Sin límite',
    start: 'INICIAR ENTRENAMIENTO',
    populationWarning: 'Poblaciones grandes pueden ralentizar equipos modestos',

    // Dashboard
    generation: 'Generación',
    bestFitness: 'Mejor',
    meanFitness: 'Media',
    worstFitness: 'Peor',
    bestEver: 'Mejor histórico',
    diversity: 'Diversidad',
    sigmaNow: 'σ actual',
    piecesPerSec: 'piezas/s',
    eta: 'ETA generación',
    agentsProgress: 'Agentes: {done}/{total}',
    stop: 'Detener',
    stopConfirm: '¿Detener el entrenamiento?',
    stopAndSave: 'Detener y guardar mejor modelo',
    stopNoSave: 'Detener sin guardar',
    saveModel: 'Guardar modelo',
    modelSaved: 'Modelo guardado: {name}',
    sessionSaved: 'Sesión guardada',
    speedMax: 'MÁX',
    headlessNote: 'Velocidad máxima: simulación sin tableros (solo estadísticas)',
    sortGrid: 'Ordenar',
    sortByIndex: 'Por índice',
    sortByFitness: 'Por fitness',
    plusOneGen: '+1 generación',
    autoSave: 'Autoguardado',
    charts: { fitness: 'Fitness', diversity: 'Diversidad', sigma: 'σ / tasa' },
    percentileBand: 'Banda p25–p75',
    ranking: 'Ranking en vivo',
    rankCols: { agent: 'Agente', fitness: 'Fitness', lines: 'Líneas', pieces: 'Piezas', status: 'Estado' },
    statusPlaying: 'Jugando',
    statusDone: 'Terminado',
    eventLog: 'Registro de eventos',
    events: {
      record: 'Nuevo récord: {best} (gen {generation})',
      'sigma-up': 'Estancamiento: σ sube a {sigma}',
      'sigma-down': 'Progreso: σ baja a {sigma}',
      injection: 'Inyección de diversidad: {injected} nuevos, {hypermutated} hipermutados',
      'diversity-collapse': 'Colapso de diversidad detectado ({diversity})',
      'curriculum-up': 'Curriculum: límite de piezas sube a {maxPieces}',
      autosave: 'Autoguardado (gen {generation})',
      recordSaved: 'Récord guardado automáticamente',
      hof: 'Añadido al Salón de la Fama (gen {generation})',
      stopCondition: 'Condición de parada alcanzada',
    },
    tuner: {
      title: 'Auto-ajuste',
      state: 'Estado',
      stagnation: 'Estancamiento',
      gens: '{n} gen.',
      trendUp: 'explorando (σ↑)',
      trendDown: 'explotando (σ↓)',
      reasons: {
        progress: 'Progreso: afinando en torno al mejor',
        'stagnation-soft': 'Estancamiento: ampliando la búsqueda',
        'stagnation-hard': 'Estancamiento largo: inyectando diversidad',
        'diversity-collapse': 'Diversidad baja: inyectando nuevos genomas',
        curriculum: 'Población domina el límite: subiendo dificultad',
      },
    },
    inspector: {
      title: 'Agente {id}',
      network: 'Red neuronal',
      featuresLive: 'Features de entrada',
      decision: 'Decisión',
      chosen: 'Elegida: rot {rot}, col {col}{hold}',
      viaHold: ' (con reserva)',
      candidatesEvaluated: '{n} colocaciones evaluadas',
      close: 'Cerrar inspector',
    },
    heatmap: 'Mapa de calor de colocaciones',
    exportHistory: 'Exportar historial',
    hallOfFame: 'Salón de la Fama',
    leaveWarning: 'Hay un entrenamiento en curso. Si sales, perderás el progreso no guardado.',
  },

  watch: {
    title: 'Ver IA',
    selectorTitle: 'Modelos guardados',
    empty: 'No hay modelos guardados. Entrena uno en el modo Entrenamiento o importa un fichero.',
    importModel: 'Importar modelo',
    importOk: 'Modelo importado: {name}',
    dropHint: 'También puedes arrastrar un fichero .json aquí',
    sortBy: 'Ordenar por',
    sortOptions: { fitness: 'Fitness', date: 'Fecha', name: 'Nombre' },
    filter: 'Buscar…',
    genShort: 'gen {n}',
    watchBtn: 'Ver jugar',
    compareBtn: 'Comparar',
    tournamentBtn: 'Torneo',
    duelBtn: 'Duelo',
    exportBtn: 'Exportar',
    deleteConfirm: '¿Eliminar «{name}»? Esta acción no se puede deshacer.',
    modelCard: 'Ficha técnica',
    archLabel: 'Arquitectura',
    weightsLabel: 'Pesos',
    originConfig: 'Configuración de origen',
    notes: 'Notas',
    tags: 'Etiquetas',
    favorite: 'Favorito',
    modelStats: 'Partidas vistas: {games} · Mejor: {best} líneas',

    // Viewer
    stepBtn: 'Paso',
    backBtn: 'Atrás',
    instant: 'Instantáneo',
    newSeed: 'Nueva semilla',
    sameSeed: 'Misma semilla',
    features: 'Features en vivo',
    network: 'Red neuronal',
    toggleNetwork: 'Mostrar/ocultar red (N)',
    decision: 'Decisión',
    candidates: 'Candidatas (top {n})',
    confidence: 'Confianza',
    confidenceHigh: 'decisión clara',
    confidenceMid: 'decisión moderada',
    confidenceLow: 'decisión reñida',
    whyChosen: 'Por qué',
    contribution: 'Contribución por feature',
    vsSecond: '1ª frente a 2ª opción',
    holdUsed: 'Usa la reserva',
    decisionLog: 'Historial de decisiones',
    heuristicOverlay: 'Ver huecos y alturas',
    heatmap: 'Mapa de calor',
    featureImportance: 'Importancia de features (partida)',
    criticalMoments: 'Momentos críticos',
    liveStats: 'Estadísticas',
    holes: 'Huecos',
    avgHeight: 'Altura media',
    vsHistory: 'Mejor que el {pct}% de sus partidas',

    // Benchmark
    benchmark: 'Benchmark',
    benchmarkTitle: 'Benchmark de {name}',
    benchmarkGames: 'Nº de partidas',
    benchmarkRun: 'Ejecutar',
    benchmarkRunning: 'Partida {i}/{n}…',
    benchmarkCancel: 'Cancelar (conserva parciales)',
    benchmarkResults: 'Resultados',
    mean: 'Media',
    stdDev: 'Desviación',
    min: 'Mínimo',
    max: 'Máximo',
    histogram: 'Histograma de líneas',
    survival: 'Curva de supervivencia',
    exportCsv: 'Exportar CSV',
    screenshot: 'Captura PNG',

    // Compare / tournament / duel
    compareTitle: 'Comparador',
    samePieces: 'Misma secuencia de piezas',
    scoreboard: 'Marcador',
    leader: 'Va ganando {name}',
    tied: 'Empate',
    tournamentTitle: 'Torneo',
    tournamentPick: 'Elige 2 o más modelos',
    gamesPerModel: 'Partidas por modelo',
    runTournament: 'Empezar torneo',
    tournamentChampion: 'Campeón: {name}',
    consistency: 'Consistencia',
    duelTitle: 'Duelo: Humano vs IA',
    duelHuman: 'Tú',
    duelAi: 'IA',
    duelHandicap: 'Velocidad de la IA',
    duelStart: 'Empezar duelo',
    duelWin: '¡HAS GANADO!',
    duelLose: 'La IA gana…',
    duelTie: 'Empate técnico',
    rematch: 'Revancha (misma semilla)',
  },
};

/** Tiny template helper: fmt('COMBO ×{n}', {n: 5}) → 'COMBO ×5' */
export function fmt(template, params = {}) {
  return template.replace(/\{(\w+)\}/g, (_, k) => (params[k] !== undefined ? params[k] : `{${k}}`));
}
